DELETE FROM product;
DELETE FROM store;
DELETE FROM categorie;
DELETE FROM assoc_product_store;
DELETE FROM assoc_product_categorie;
DELETE FROM backup;
ALTER SEQUENCE product_id_seq RESTART WITH 1;
ALTER SEQUENCE categorie_id_seq RESTART WITH 1;
ALTER SEQUENCE store_id_seq RESTART WITH 1;
ALTER SEQUENCE backup_number_seq RESTART WITH 1;